version: "3.9"
services:
  ${APP_NAME}:
    image: "${APP_NAME}:test"
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    environment:
      RUN_MODE: "test"
      KILL_SERVER_PORT: "6666"
      # Your ENV config here
    depends_on:
      - db
    tty: true
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
